<a href="https://colab.research.google.com/github/Harikrishnan0708/sripi/blob/main/Exercise2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[link text](https://)1.variable and datatype

In [ ]:
x=5
y=7
x,y=y,x
print("after swping:",x,y)

after swping: 7 5


2. Lists - Nested Lists
You have a nested list:
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
a) Extract and print the middle element from the nested list.
b) Flatten the list into a single list [1, 2, 3, 4, 5, 6, 7, 8, 9] without using loops.

In [ ]:
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(data[1])
print(data[1][1])
single_list=(data[0]+data[1]+data[2])
print(single_list)

[4, 5, 6]
5
[1, 2, 3, 4, 5, 6, 7, 8, 9]


3. Tuples - Tuple Unpacking
Given:
values = (100, 200, 300)
a) Unpack this tuple into three variables and print them.
b) Swap the values without using a temporary variable.

In [ ]:
values = (100, 200, 300)
a,b,c=values
print(a,b,c)
a,b=b,a
print(a,b)

100 200 300
200 100


4. Dictionary - Complex Keys
Create a dictionary where:
Keys are tuples representing (x, y) coordinates.
Values are the sum of x and y.
Example:
{ (1,2): 3, (3,4): 7, (5,6): 11 }
Write a function to retrieve the sum for a given coordinate.

In [ ]:
 dict1={ (1,2): 3, (3,4): 7, (5,6): 11 }
 print(dict1)
 x=int(input("enter the x co-ordinate:"))
 y=int(input("enter the y co-ordinate:"))
def retreive_sum(a,b):
    for key,value in dict1.items():
      if(key ==(x,y)):
        print(value)
retreive_sum(x,y)

{(1, 2): 3, (3, 4): 7, (5, 6): 11}
enter the x co-ordinate:1
enter the y co-ordinate:2
3


5. Functions - Nested Functions
Write a function outer_function(a, b) that:
Contains an inner function to calculate a² + b².
Returns the result.
Call outer_function(3, 4) and print the result.

In [ ]:
def outer_fuction(a,b):
  def inner_function():
    return a**2+b**2
  return inner_function()
print(outer_fuction(3,4))

25


6. Functions - Lambda & Map
You are given a list:
numbers = [1, 2, 3, 4, 5]
Use a lambda function and map() to generate a list where each number is cubed.

In [ ]:
numbers = [1, 2, 3, 4, 5]
print(list(map(lambda x:x**3,numbers)))

[1, 8, 27, 64, 125]


7. Functions - Recursion
Write a recursive function to calculate the sum of digits of a given number.
Example:
Input: 1234
Output: 10  (1+2+3+4)

In [ ]:
def sum(n):
  if n ==0:
    return 0
  return n% 10 + sum(n//10)
n=int(input("enter the num:"))
print("sum of digits:",sum(n))

enter the num:1234
sum of digits: 10


8. List Comprehensions
Generate a list of all numbers between 1 and 100 that:
Are divisible by 5
But not by 3
Use list comprehension.

In [ ]:
list_comp=[x for x in range(101)if x %5==0and x %3!=0]
print(list_comp)

[5, 10, 20, 25, 35, 40, 50, 55, 65, 70, 80, 85, 95, 100]


<>:1: SyntaxWarning: invalid decimal literal
<>:1: SyntaxWarning: invalid decimal literal
<ipython-input-11-1da68997533e>:1: SyntaxWarning: invalid decimal literal
  list_comp=[x for x in range(101)if x %5==0and x %3!=0]


9. Dictionary - Sorting by Values
Given:
scores = {"Alice": 90, "Bob": 85, "Eve": 92}
Sort this dictionary by values in descending order and print the result.

In [ ]:
scores = {"Alice": 90, "Bob": 85, "Eve": 92}
desc_order_sc=dict(sorted(scores.items(),key=lambda x:x[1],reverse=True))
print(desc_order_sc)

{'Eve': 92, 'Alice': 90, 'Bob': 85}


10. Sets - Unique Characters
Write a Python function that takes a string as input and returns:
A set of unique characters in the string.
The number of unique characters.
Example:
Input: "hello"
Output: {'h', 'e', 'l', 'o'}, 4

In [ ]:
str1="hello"
str2=set(str1)
print(str2)

{'h', 'o', 'l', 'e'}


11. Tuples - Finding Common Elements
Given two tuples:
t1 = (1, 2, 3, 4, 5)
t2 = (4, 5, 6, 7, 8)
Find and print the common elements.

In [ ]:
t1 = (1, 2, 3, 4, 5)
t2 = (4, 5, 6, 7, 8)
common=tuple(set(t1)&set(t2))
print(common)

(4, 5)


12. Dictionary - Reverse Key-Value Mapping
Given a dictionary:
data = {"A": 1, "B": 2, "C": 3}
Write a program to swap keys and values:
Output: {1: "A", 2: "B", 3: "C"}

In [ ]:
data = {"A": 1, "B": 2, "C": 3}
swapped_data={j:i for i,j in data.items()}
print(swapped_data)

{1: 'A', 2: 'B', 3: 'C'}


13. Functions - Multiple Return Values
Write a function that takes two numbers as input and returns:
.Their sum
.Their difference
.Their product
.Their quotient
Print all four results.

In [ ]:
def calculator(a,b):
  print("the sum is:",a+b,"\n the diff is:",a-b,"\n the product is",a*b,"\n he quotient is:",a//b)
calculator(2,3)

the sum is: 5 
 the diff is: -1 
 the product is 6 
 he quotient is: 0


14. List - Finding Second Largest Number
Write a function to find the second largest number in a given list without using sort().
Example:
Input: [10, 20, 4, 45, 99]
Output: 45

In [ ]:
list1=[10,20,4,45,99]
list1.sort(reverse=True)
print(list1[1])

45


15. List - Pair Sum Problem
Given a list of numbers and a target sum, find all pairs in the list that add up to the target.
Example:
Input: [2, 4, 3, 7, 1, 9], Target: 10
Output: [(3, 7), (1, 9)]

In [ ]:
l=[2, 4, 3, 7, 1, 9]
tar =10
ans=[]
seen=set()

for n in l:
  second =tar-n
  if second in seen:
      ans.append((n,second))
  seen.add(n)
print(ans)

[(7, 3), (9, 1)]


16. Pandas - Filtering DataFrame
You are given the following Pandas DataFrame:
import pandas as pd
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [24, 27, 22, 32],
    "Score": [85, 90, 78, 88]
})
Write a one-liner to filter and display only rows where Age is greater than 25.

In [ ]:
import pandas as pd
df = pd.DataFrame({ "Name": ["Alice", "Bob", "Charlie", "David"],
                   "Age": [24, 27, 22, 32], "Score": [85, 90, 78, 88]
})
df1=df[df["Age"]>=25]
display(df1)

Name  Age  Score
1    Bob   27     90
3  David   32     88

17. Pandas - Group By Operation
You have the following DataFrame:
df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Salary": [70000, 50000, 80000, 60000, 52000]
})
Write a Pandas command to calculate the average salary per department.

In [ ]:
df = pd.DataFrame({ "Department": ["IT", "HR", "IT", "Finance", "HR"],
                    "Salary": [70000, 50000, 80000, 60000, 52000]
})
df["Salary"].mean()

np.float64(62400.0)

18. NumPy - Create a 5x5 Matrix
Write a program to create a 5x5 NumPy matrix where:
The diagonal elements are 1
All other elements are 0
Example:
Output:
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]

In [ ]:
import numpy as np
array=np.zeros((5,5,),int)
np.fill_diagonal(array,1)
print(array)


[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


19. NumPy - Element-wise Operations
Given two NumPy arrays:
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
Perform element-wise:
*.Addition
*.Multiplication
*.Power (a^b)
Print the results.

In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

add_ans=np.add(a,b)
mul_ans=np.multiply(a,b)
pow_ans=np.power(a,b)
print("add:",add_ans,"\n mulitiplication:",mul_ans,"/n power:",pow_ans)

add: [11 22 33 44] 
 mulitiplication: [ 10  40  90 160] /n power: [              1         1048576 205891132094649               0]


20. NumPy - Find Index of Maximum Value
Given:
arr = np.array([10, 25, 39, 50, 19])
Write a one-liner to find the index of the maximum value.

In [ ]:
arr=np.array([10,25,39,50,29])
print(arr.argmax())

3
